### ISSUE TITLE
Ruby script for kumar_asshole.rb fails

### ISSUE THREAD

**Issue by bitsapien** [NARKOZ/hacker-scripts#53]
The script fails with this message :
```
kumar_asshole.rb:21:in `block in <main>': undefined method `[]' for #<Mail::Body:0x007fd4bda2be50> (NoMethodError)
```

**Comment by bitsapien** [comment]
Found solution for the above, needed to replace `email.body` with `email.body.raw_source`, now I have a different problem. I get this:
```
kumar_asshole.rb:26:in `block in <main>': undefined method `create_reply' for main:Object (NoMethodError)

```
