### ISSUE TITLE
Ruby script still fails

### ISSUE THREAD

**Issue by bitsapien** [NARKOZ/hacker-scripts#57]
The script now fails with the following error message : 
```
kumar_asshole.rb:18:in `create_reply': undefined local variable or method `gmail' for main:Object (NameError)
	from kumar_asshole.rb:36:in `block in <main>'
	from kumar_asshole.rb:25:in `each'
	from kumar_asshole.rb:25:in `<main>'
```

**Comment by bitsapien** [comment]
There is no harm in turning `kumars_email` and `gmail` to constants. I will create a pull request in a moment with the working changes.

**Comment by AbhimanyuAryan** [comment]
did he wrote fucking.rb?

**Comment by bitsapien** [comment]
Eh? :confused:

**Comment by NARKOZ** [comment]
Merged, thank you.
